### ISSUE TITLE
Bug: IndexError: list assignment index out of range

### ISSUE THREAD

**Issue by RubeRad** [RubeRad/MarcoMD#18]
playing with settings.nblocks=3 this bug almost always crashes the game before you can finish:

Traceback (most recent call last):
  File "./MarcoMD.py", line 40, in <module>
    movers = events.clear(settings, statics)
  File "/home/tina/src/MarcoMD/events.py", line 83, in clear
    inarows = detect_inarows(settings, statics)
  File "/home/tina/src/MarcoMD/events.py", line 46, in detect_inarows
    colors[r][c] = s.colors[i]
IndexError: list assignment index out of range

**Comment by RubeRad** [comment]
Seems to have been resolved by PR #20/Issue #17
